### ISSUE TITLE
Please describe in detail how to install

### ISSUE THREAD

**Issue by NaokiSato102** [valerytschopp/ubuntu-mswinurl#1]
I installed it by make install, but could you please post the official method?

This app has solved a little, rather irritating problem that had been bothering me for a long time. Thank you.

**Comment by valerytschopp** [comment]
Hey @NaokiSato102 I've created Debian/Ubuntu package `mswinurl_1.0-1_all.deb`, you can find it in the `packages` directory. Is it something you can use?

1. download the package mswinurl_1.0-1_all.deb
2. install it with `sudo dpkg -i mswinurl_1.0-1_all.deb`

**Comment by pzmarzly** [comment]
The package file worked for me. On newer versions of Ubuntu, you can use `apt install ./mswinurl_1.0-1_all.deb` instead of `dpkg`, too.

I think you should add a link to it in README, to make it more visible.

**Comment by valerytschopp** [comment]
The README.md is updated to include the installation information
