### ISSUE TITLE
Perform database updates during installation

### ISSUE THREAD

**Issue by NaokiSato102** [valerytschopp/ubuntu-mswinurl#2]
I think it would be more convenient to perform a database update at the time of installation so that it can be adapted without having to reboot.
I think you should do
 "update-mime-database /usr/share/mime" 
and
 "update-desktop-database".

**Comment by valerytschopp** [comment]
The changes in the [debian/postinst](/valerytschopp/ubuntu-mswinurl/blob/master/debian/postinst) file solves this issue
